Fix: instantiate InteractionHandler instead of storing class reference
bot.js was storing the InteractionHandler class (not an instance) on
the bot instance, causing 'TypeError: handleSelectMenu is not a function'
when select menu or modal events fired, since instance methods were
called as static methods.